### PR TITLE
DOC: Adds guide to use `-f` flag to modify default config.

### LINKED ISSUE #454: DOC: Add more documentation about custom configuration.
Users can specify custom configuration using `-f` option when deploy Xorbits, there should be some examples to show users how to override default options.

### PR DESCRIPTION
**Pull request by shark-21**
## What do these changes do?
It is a guide with an example to override default config by using -f flag in documentation.

## Related issue number

Fixes #454

### CODE REVIEW

**Comment by aresnow1** [comment]
We've seen your pull request, and will review recently, don't close pull request and open another one.

**Review by aresnow1 — APPROVED** [review]
LGTM

**Comment by shark-21** [comment]
Really sorry for the inconvenience. I was facing an issue with git, all of my previous commits in xorbits were getting included in this pr. So I had to close previous 2 prs and sort that issue. I sorted it out yesterday. Thanks and again sorry for the inconvenience.

**Comment by aresnow1** [comment]
> Really sorry for the inconvenience. I was facing an issue with git, all of my previous commits in xorbits were getting included in this pr. So I had to close previous 2 prs and sort that issue. I sorted it out yesterday. Thanks and again sorry for the inconvenience.

It's okay, still very much appreciate your contribution.

**Pull request merged**
