### PR TITLE
BLD: Fixes cython compilation failures in Python 3.11.

### LINKED ISSUE #251: BUG: _cython_blas.pyx:111:27: Converting to Python object not allowed without gil
### Describe the bug

I'm encountering errors as follows with Python 3.11 and cython==0.29.26. I would like to confirm whether it is a known issue.

(Homebrew on MacOS has upgraded the default Python version to 3.11)

```python
xorbits/_mars/learn/utils/_cython_blas.pyx:111:20: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

cdef void _rot(int n, floating *x, int incx, floating *y, int incy,
               floating c, floating s) nogil:
    """Apply plane rotation"""
    if floating is float:
        srot(&n, x, &incx, y, &incy, &c, &s)
                          ^
------------------------------------------------------------

xorbits/_mars/learn/utils/_cython_blas.pyx:111:27: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

cdef void _rot(int n, floating *x, int incx, floating *y, int incy,
               floating c, floating s) nogil:
    """Apply plane rotation"""
    if floating is float:
        srot(&n, x, &incx, y, &incy, &c, &s)
                             ^
------------------------------------------------------------

xorbits/_mars/learn/utils/_cython_blas.pyx:111:30: Converting to Python object not allowed without gil

Error compiling Cython file:
------------------------------------------------------------
...

cdef void _rot(int n, floating *x, int incx, floating *y, int incy,
               floating c, floating s) nogil:
    """Apply plane rotation"""
    if floating is float:
        srot(&n, x, &incx, y, &incy, &c, &s)
```

### PR DESCRIPTION
**Pull request by sighingnow**
## What do these changes do?

Note that CI is not updated.

## Related issue number

Fixes #251

### CODE REVIEW

**Comment by sighingnow** [comment]
I have attched links in comments for reference.

**Comment by aresnow1** [comment]
Thanks for your fix, I'll add an action workflow for Python 3.11 later in this PR.

**Comment by aresnow1** [comment]
It looks like there are other compilation issues, I'm trying to address them.

**Comment by sighingnow** [comment]
Cannot reproduce the build failure on CI with conda's Python 3.11 (`conda create -n xorbits python=3.11`).

**Review by aresnow1 — APPROVED** [review]
LGTM

**Pull request merged**
