### PR TITLE
ENH: implement synchronous SGD for Logistic Regression

### PR DESCRIPTION
**Pull request by RandomY-2**
## What do these changes do?

Now during each iteration of the fit function, we partition the inputs based on rows and compute individual gradients instead of computing the entire gradient in one call. The computation should still be the same. Essentially, the ```1/N * sum(``` part of ```dW``` is put outside, and each row is calculated separately. So I think the maths should be correct.

Test code:

```python
import time
from sklearn.datasets import load_iris
from xorbits._mars.learn.glm import LogisticRegression

X, y = load_iris(return_X_y=True)

start = time.time()
clf = LogisticRegression(random_state=0, max_iter=3).fit(X, y)
print(clf.predict(X[:2, :]))
print(time.time() - start)
```

Before = 17.836988925933838
Now = 5.583844184875488

I had to use numpy methods because I got random errors when I try to send mars tensors inside mars remote (python version = 3.9.12). For example:

```python
import xorbits._mars.tensor as mt
import xorbits._mars.remote as mr

def test(a):
    a = a.reshape((1, 5))
    return a

l = mr.ExecutableTuple([mr.spawn(test, args=(mt.ones((5, 1)))) for _ in range(10)]).execute().fetch()

print(mt.sum(l, axis=0).execute().fetch())
```

This gives a ```KeyError: 'c3229365608b2f44b218cf44b490e6bd_0'``` when I try to run it, whereas

```python
import xorbits._mars.tensor as mt
import xorbits._mars.remote as mr

def test(a):
    a = a.reshape((1, 5))
    return a
                                                          # only change
l = mr.ExecutableTuple([mr.spawn(test, args=(mt.ones((5, 1)).to_numpy())) for _ in range(10)]).execute().fetch()

print(mt.sum(l, axis=0).execute().fetch())

```

works as expected.

## Related issue number

Fixes #xxxx

## Check code requirements

- [x] tests added / passed (if needed)
- [x] Ensure all linting tests pass

### CODE REVIEW

**Comment by aresnow1** [comment]
Pandas 2.0 released, there are some compatibility issues, we temporarily fixed Pandas version first #322.

**Comment by aresnow1** [comment]
About the `KeyError`, it seems a bug, the key of `mt.ones((5, 1))` is always same, I guess it caused data to be deleted by mistake. The following code can be executed:
``` Python
In [2]: import xorbits._mars.tensor as mt
   ...: import xorbits._mars.remote as mr
   ...:
   ...: def test(a, i):
   ...:     a = a.reshape((i, 5))
   ...:     return a
   ...:
   ...: l = mr.ExecutableTuple([mr.spawn(test, args=(mt.ones((5, i)), i)) for i in range(10)]).execute()
   ...:
100%|████████████████████████████████████████████████████████████████████████████| 100.00/100 [00:00<00:00, 1194.22it/s]

```

**Comment by aresnow1** [comment]
`to_numpy` will fetch all data to client which is very likely to cause OOM. We should find a way to avoid calling `to_numpy`, and keep data in cluster.

**Comment by RandomY-2** [comment]
i changed to mars tensors now, but the executions seem to create more overheads so the time is actually worse now on my computer (around 32 seconds, vs originally = 17 seconds)... although the computation graph seems to be more parallel. maybe separating them into individual tasks isn't too advantageous.

image

originally: 
image

**Comment by RandomY-2** [comment]
Actually, when I tested with more iterations, this paralleled version begins to finish faster - 10 epochs = 100 vs 73 (1.369), 20 epochs = 203 vs 219 (0.926), 40 epochs = 388 vs 820 (0.47), so i guess it works

**Comment by aresnow1** [comment]
Great attempt! let me see why the first few iterations were slow.

**Comment by aresnow1** [comment]
Could you provide your test code?

**Comment by RandomY-2** [comment]
just the same test code with max_iter changed to larger numbers. so like 40 iterations would be 

```python
import time
from sklearn.datasets import load_iris
from xorbits._mars.learn.glm import LogisticRegression

X, y = load_iris(return_X_y=True)

start = time.time()
clf = LogisticRegression(random_state=0, max_iter=40).fit(X, y)
print(clf.predict(X[:2, :]))
print(time.time() - start)
```

which takes ~380 seconds on my computer, and the original version takes 800+ seconds

**Comment by RandomY-2** [comment]
I tried to reduce the initial slow training time but have had no luck. but for larger datasets such as ```sklearn.dataset.load_digits```, even for iterations=3, the paralleled version still finishes faster (375 vs 750). perhaps for the iris case, the dataset is just too small, so when the number of iterations is small, the overhead for creating those executions etc outweighs the pros, but for larger datasets, this update definitely reduces the time.

**Review by aresnow1 — APPROVED** [review]
LGTM

**Review by qianduoduo0904 — APPROVED** [review]
LGTM

**Pull request merged**
