### PR TITLE
BLD: Docker image supports multi python versions

### LINKED ISSUE #157: BLD: Release Xorbits docker images for multi python versions that we support
Note that the issue tracker is NOT the place for general support.  For
discussions about development, questions about usage, or any general questions,
contact us on https://discuss.xorbits.io/.

Docker image supports multi python versions.

### PR DESCRIPTION
**Pull request by ChengjieLi28**
Support python 3.7, 3.8, 3.9 and 3.10 for every docker image release.

Resolves #157 

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass

### CODE REVIEW

**Review by qianduoduo0904 — APPROVED** [review]
LGTM

**Comment by aresnow1** [comment]
Do we need test them in CI?

**Review by aresnow1 — APPROVED** [review]
LGTM

**Review by qianduoduo0904 — APPROVED** [review]
LGTM

**Pull request merged**
