### PR TITLE
BLD: add doc deps to setup.cfg

### LINKED ISSUE #466: BUG: failed to install doc requirements on Apple M1
### Describe the bug
The doc requirements include `lightgbm>=3.0.0`. But installing lightgbm on Apple M1 could result in an error.

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version
2. The version of Xorbits you use
3. Versions of crucial packages, such as numpy, scipy and pandas
4. Full stack of the error.
```python
      Traceback (most recent call last):
        File "/private/var/folders/2p/lb2j30s116zgq01tny9srvbw0000gn/T/pip-install-6kmldwi9/lightgbm_ea8fe0e250774541b5bfaba97a9cc4c3/setup.py", line 95, in silent_call
          subprocess.check_call(cmd, stderr=log, stdout=log)
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', '_lightgbm', '-I/private/var/folders/2p/lb2j30s116zgq01tny9srvbw0000gn/T/pip-install-6kmldwi9/lightgbm_ea8fe0e250774541b5bfaba97a9cc4c3/build_cpp', '-j4']' returned non-zero exit status 2.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/2p/lb2j30s116zgq01tny9srvbw0000gn/T/pip-install-6kmldwi9/lightgbm_ea8fe0e250774541b5bfaba97a9cc4c3/setup.py", line 334, in <module>
          setup(name='lightgbm',
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 360, in run
          self.run_command("install")
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/2p/lb2j30s116zgq01tny9srvbw0000gn/T/pip-install-6kmldwi9/lightgbm_ea8fe0e250774541b5bfaba97a9cc4c3/setup.py", line 248, in run
          compile_cpp(use_mingw=self.mingw, use_gpu=self.gpu, use_cuda=self.cuda, use_mpi=self.mpi,
        File "/private/var/folders/2p/lb2j30s116zgq01tny9srvbw0000gn/T/pip-install-6kmldwi9/lightgbm_ea8fe0e250774541b5bfaba97a9cc4c3/setup.py", line 199, in compile_cpp
          silent_call(["make", "_lightgbm", f"-I{build_dir}", "-j4"], raise_error=True,
        File "/private/var/folders/2p/lb2j30s116zgq01tny9srvbw0000gn/T/pip-install-6kmldwi9/lightgbm_ea8fe0e250774541b5bfaba97a9cc4c3/setup.py", line 99, in silent_call
          raise Exception("\n".join((error_msg, LOG_NOTICE)))
      Exception: An error has occurred while building lightgbm library file
      The full version of error log was saved into /Users/jon/LightGBM_compilation.log
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lightgbm
  error: subprocess-exited-with-error

  × Running setup.py install for lightgbm did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      INFO:root:running install
      /Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      INFO:LightGBM:Starting to compile the library.
      INFO:LightGBM:Starting to compile with CMake.
      Traceback (most recent call last):
        File "/private/var/folders/2p/lb2j30s116zgq01tny9srvbw0000gn/T/pip-install-6kmldwi9/lightgbm_ea8fe0e250774541b5bfaba97a9cc4c3/setup.py", line 95, in silent_call
          subprocess.check_call(cmd, stderr=log, stdout=log)
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', '_lightgbm', '-I/private/var/folders/2p/lb2j30s116zgq01tny9srvbw0000gn/T/pip-install-6kmldwi9/lightgbm_ea8fe0e250774541b5bfaba97a9cc4c3/build_cpp', '-j4']' returned non-zero exit status 2.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/2p/lb2j30s116zgq01tny9srvbw0000gn/T/pip-install-6kmldwi9/lightgbm_ea8fe0e250774541b5bfaba97a9cc4c3/setup.py", line 334, in <module>
          setup(name='lightgbm',
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/Users/jon/Documents/miniconda3/envs/dev/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/2p/lb2j30s116zgq01tny9srvbw0000gn/T/pip-install-6kmldwi9/lightgbm_ea8fe0e250774541b5bfaba97a9cc4c3/setup.py", line 248, in run
          compile_cpp(use_mingw=self.mingw, use_gpu=self.gpu, use_cuda=self.cuda, use_mpi=self.mpi,
        File "/private/var/folders/2p/lb2j30s116zgq01tny9srvbw0000gn/T/pip-install-6kmldwi9/lightgbm_ea8fe0e250774541b5bfaba97a9cc4c3/setup.py", line 199, in compile_cpp
          silent_call(["make", "_lightgbm", f"-I{build_dir}", "-j4"], raise_error=True,
        File "/private/var/folders/2p/lb2j30s116zgq01tny9srvbw0000gn/T/pip-install-6kmldwi9/lightgbm_ea8fe0e250774541b5bfaba97a9cc4c3/setup.py", line 99, in silent_call
          raise Exception("\n".join((error_msg, LOG_NOTICE)))
      Exception: An error has occurred while building lightgbm library file
      The full version of error log was saved into /Users/jon/LightGBM_compilation.log
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lightgbm

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
5. Minimized code to reproduce the error.
```bash
pip install lightgbm>\=3.0.0
```

### Additional context
[LightGBM_compilation.log](https://github.com/xprobe-inc/xorbits/files/11541385/LightGBM_compilation.log)

### PR DESCRIPTION
**Pull request by UranusSeven**
## What do these changes do?
1. remove requirements-doc.txt
2. add sphinx related packages to setup.cfg which simplify the way developers install dependencies for docs.

## Related issue number

Resolves #466 

## Check code requirements

- [x] tests added / passed (if needed)
- [x] Ensure all linting tests pass

### CODE REVIEW

**Comment by qianduoduo0904** [comment]
This file is used in readthedocs configuration, see https://github.com/xprobe-inc/xorbits/blob/ce900c91a2864f9bc715029728cfd77bfeba5bdf/.readthedocs.yaml#L14-L16

**Comment by UranusSeven** [comment]
> This file is used in readthedocs configuration, see
> 
> https://github.com/xprobe-inc/xorbits/blob/ce900c91a2864f9bc715029728cfd77bfeba5bdf/.readthedocs.yaml#L14-L16


> This file is used in readthedocs configuration, see
> 
> https://github.com/xprobe-inc/xorbits/blob/ce900c91a2864f9bc715029728cfd77bfeba5bdf/.readthedocs.yaml#L14-L16

How about keeping the requirements-doc.txt while still adding the doc dependencies to setup.cfg?

**Comment by qianduoduo0904** [comment]
> > This file is used in readthedocs configuration, see
> > https://github.com/xprobe-inc/xorbits/blob/ce900c91a2864f9bc715029728cfd77bfeba5bdf/.readthedocs.yaml#L14-L16
> 
> How about keeping the requirements-doc.txt while still adding the doc dependencies to setup.cfg?

Refer to https://docs.readthedocs.io/en/stable/config-file/v2.html#packages

**Comment by UranusSeven** [comment]
> > > This file is used in readthedocs configuration, see
> > > https://github.com/xprobe-inc/xorbits/blob/ce900c91a2864f9bc715029728cfd77bfeba5bdf/.readthedocs.yaml#L14-L16
> > 
> > 
> > How about keeping the requirements-doc.txt while still adding the doc dependencies to setup.cfg?
> 
> Refer to https://docs.readthedocs.io/en/stable/config-file/v2.html#packages

Done.

**Review by qianduoduo0904 — APPROVED** [review]
LGTM

**Review by aresnow1 — APPROVED** [review]
LGTM

**Pull request merged**
