### PR TITLE
ENH: runtime stats

### PR DESCRIPTION
**Pull request by UranusSeven**
## What do these changes do?
Allow runtime stats dump.

To enable runtime stats collection, you need to trigger execution explicitly with an extra config:
```python
xorbits.run(df, extra_config={"collect_task_info": True})
```

## Check code requirements

- [x] tests added / passed (if needed)
- [x] Ensure all linting tests pass

### CODE REVIEW

**Comment by aresnow1** [comment]
Can we dump those stats to cloud storage like S3?

**Comment by UranusSeven** [comment]
> Can we dump those stats to cloud storage like S3?

Sure. Will add this feature later. See #214.

**Review by aresnow1 — APPROVED** [review]
LGTM

**Review by qianduoduo0904 — APPROVED** [review]
LGTM

**Pull request merged**
